title: HonFigurator Golden Path
description: How to set up HonFigurator with AWS
url: "https://cptwonton.github.io/Honfigurator-Golden-Path/"
baseurl: "" # Keep it empty for GitHub Pages

#theme: jekyll-theme-minimal
remote_theme: pages-themes/midnight@v0.2.0

# GitHub Pages settings
repository: HonFigurator-Golden-Path/cptwonton.github.io
branch: main

permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme 

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _site
  - .sass-cache
